package com.jarvis.ai;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.net.*;import android.provider.Settings;import android.speech.*;import android.graphics.Color;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.view.PreviewView;import java.util.*;

public class MainActivity extends AppCompatActivity{
 TextView chat,status,mode,connection,hud,coreState,offlineState;EditText input;MemoryStore memory;NotificationStore notes;AIClient ai;LanguageManager voice;OfflineEngine offline;OfflineLlmEngine localLlm;ToolRegistry tools;SecureStore secure;CameraXVisionController vision;boolean cameraOn=false;boolean replyConfirmed=false;
 BroadcastReceiver wakeReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){listenOnce();}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);
  chat=findViewById(R.id.chat);status=findViewById(R.id.status);mode=findViewById(R.id.mode);connection=findViewById(R.id.connection);hud=findViewById(R.id.hud);coreState=findViewById(R.id.coreState);offlineState=findViewById(R.id.offlineState);input=findViewById(R.id.input);
  memory=new MemoryStore(this);notes=new NotificationStore(this);ai=new AIClient();voice=new LanguageManager(this);offline=new OfflineEngine(this);localLlm=new OfflineLlmEngine(this);tools=new ToolRegistry();secure=new SecureStore(this);vision=new CameraXVisionController(this,(PreviewView)findViewById(R.id.preview));
  ai.configure(secure.get("endpoint","https://api.openai.com/v1/chat/completions"),secure.get("key",""),secure.get("model","gpt-4o-mini"),secure.get("authHeader","Authorization"),secure.get("authPrefix","Bearer"));
  findViewById(R.id.send).setOnClickListener(v->send());findViewById(R.id.voice).setOnClickListener(v->listenOnce());findViewById(R.id.camera).setOnClickListener(v->toggleCamera());findViewById(R.id.memory).setOnClickListener(v->show("حافظه بلندمدت",memory.recent(60)));findViewById(R.id.notifications).setOnClickListener(v->notificationMenu());findViewById(R.id.wake).setOnClickListener(v->toggleWake());findViewById(R.id.menu).setOnClickListener(this::menu);
  status.setText("● "+(isOnline()?"متصل به اینترنت":"آفلاین"));connection.setText((isOnline()?"AI: ● متصل":"AI: ○ قطع")+"  Offline: ● آماده");mode.setText("حالت هوشمند • زبان اصلی: فارسی • ویس: فارسی • نوشته: فارسی");hud.setText("◉ CORE READY • VISION STANDBY • MEMORY READY");coreState.setText("◉ JARVIS CORE • 1.021");offlineState.setText("آفلاین: آماده");
  append("جارویس","سلام! من جارویس 1.021 هستم. زبان اصلی من فارسی است و تا وقتی تغییرش ندهی فارسی می‌مانم.");
  offlineState.setText("آفلاین: مدل هنگام نیاز بارگذاری می‌شود");
  if(!"1".equals(secure.get("activated","")))new Handler().postDelayed(this::passwordGate,450);
  registerReceiver(wakeReceiver,new IntentFilter("com.jarvis.ai.WAKE"),Context.RECEIVER_NOT_EXPORTED);
  if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},77);
  updateConnectionLoop();
 }
 void updateConnectionLoop(){status.setText("● "+(isOnline()?"متصل به اینترنت":"آفلاین"));connection.setText((isOnline()?"AI: ● متصل":"AI: ○ قطع")+"  Offline: ● آماده");new Handler().postDelayed(this::updateConnectionLoop,5000);}
 boolean isOnline(){return ((ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE)).getActiveNetwork()!=null;}
 void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");append("شما",q);memory.add("user",q);
  String local=offline.answer(q);if(local!=null){respond(local);return;}
  String l=q.toLowerCase(Locale.ROOT);
  if(l.startsWith("باز کن ")||l.startsWith("open ")||l.startsWith("اجرا ")||l.startsWith("do ")){String a=q.replaceFirst("(?i)^(باز کن|open|اجرا|do)\\s*","");respond(tools.execute(this,a));return;}
  if(l.contains("پاسخ پیام")||l.contains("به پیام")||l.contains("reply message")){confirmReply();return;}
  if(isOnline()){ai.ask("تو JARVIS هستی. همیشه فارسی پاسخ بده مگر کاربر صریحاً زبان دیگری بخواهد. طبیعی، دقیق و کوتاه. کاربر: "+q+"\nحافظه مرتبط:\n"+memory.recent(18),this::respond);}
  else{offlineState.setText("آفلاین: در حال فکر کردن");localLlm.ask(q,memory.recent(18),s->{offlineState.setText("آفلاین: مدل آماده");respond(s);});}
 }
 void respond(String s){append("جارویس",s);memory.add("assistant",s);voice.speak(s,.95f);}
 void listenOnce(){if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},8);return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"fa-IR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);startActivityForResult(i,99);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==99&&c==RESULT_OK&&d!=null){ArrayList<String>x=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));send();}}}
 void toggleCamera(){if(checkSelfPermission(android.Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.CAMERA},42);return;}cameraOn=!cameraOn;findViewById(R.id.preview).setVisibility(cameraOn?View.VISIBLE:View.GONE);findViewById(R.id.cameraDim).setVisibility(cameraOn?View.VISIBLE:View.GONE);if(cameraOn){vision.start();((Button)findViewById(R.id.camera)).setText("👁 تحلیل تصویر");findViewById(R.id.camera).setOnClickListener(v->vision.shot(ai,this::respond));hud.setText("◉ VISION / LIVE • دوربین فعال");}else{vision.stop();((Button)findViewById(R.id.camera)).setText("👁 دوربین زنده");findViewById(R.id.camera).setOnClickListener(v->toggleCamera());hud.setText("◉ CORE READY • VISION STANDBY");}}
 void toggleWake(){if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},8);return;}try{startForegroundService(new Intent(this,JarvisVoiceService.class));status.setText("● Hey JARVIS فعال • سرویس پس‌زمینه");respond("گوش‌به‌زنگ شدم. بگو Hey JARVIS.");}catch(Exception e){respond("برای فعال‌سازی ویس پس‌زمینه باید از داخل برنامه و با مجوز میکروفون شروع شود.");}}
 void menu(View v){PopupMenu p=new PopupMenu(this,v);String[] opts={"🤖 حالت‌های پشت‌صحنه","🌐 زبان اصلی: فارسی","🎙 زبان ویس: فارسی","⌨ زبان نوشته: فارسی","🎨 شخصی‌سازی ظاهر","🧠 وضعیت مدل آفلاین","📱 برنامه‌ها و فرمان‌ها","💬 پیام‌های دریافتی","🔐 امنیت و رمز","⚙ تنظیمات هوش مصنوعی","🛡 مجوزهای Android","ℹ درباره JARVIS 1.021"};for(String x:opts)p.getMenu().add(x);p.setOnMenuItemClickListener(i->{String s=i.getTitle().toString();if(s.contains("شخصی"))customize();else if(s.contains("هوش مصنوعی"))setupAI();else if(s.contains("مجوز"))permissionMenu();else if(s.contains("پیام"))notificationMenu();else if(s.contains("پشت"))backgroundMenu();else if(s.contains("مدل"))show("مدل آفلاین","Qwen محلی داخل APK قرار دارد و برای پاسخ‌گویی بدون اینترنت استفاده می‌شود.");else if(s.contains("برنامه"))show("فرمان‌ها","نمونه‌ها: «باز کن Chrome»، «باز کن YouTube»، «Wi-Fi»، «تنظیمات»، «خانه»، «برگرد»، «برنامه‌های اخیر».");else if(s.contains("امنیت"))show("امنیت","رمز فعال‌سازی اولیه: ayhan2012. کلید API در فضای رمزنگاری‌شده Android نگهداری می‌شود.");else if(s.contains("زبان"))show("زبان","فارسی زبان پیش‌فرض است. تنظیمات زبان ویس و نوشته نیز در این منو قابل تغییر است.");else show("JARVIS 1.021","هسته فارسی • LLM آفلاین • Vision • Wake Word • Tools • Memory • Android Control");return true;});p.show();}
 void backgroundMenu(){new AlertDialog.Builder(this).setTitle("حالت‌های پشت‌صحنه").setMultiChoiceItems(new String[]{"اعلان‌ها و خلاصه پیام‌ها","Wake Word / Hey JARVIS","حافظه بلندمدت","به‌روزرسانی وضعیت اتصال"},new boolean[]{true,"1".equals(secure.get("wake","")),true,true},(d,w,c)->{}).setPositiveButton("فعال‌سازی",(d,w)->{secure.put("wake","1");respond("حالت‌های پشت‌صحنه تنظیم شدند.");}).setNegativeButton("لغو",null).show();}
 void permissionMenu(){new AlertDialog.Builder(this).setTitle("مجوزها").setItems(new String[]{"🎙 میکروفون","👁 دوربین","💬 دسترسی اعلان‌ها","📱 دسترسی Accessibility"},(d,w)->{if(w==0)requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},8);else if(w==1)requestPermissions(new String[]{android.Manifest.permission.CAMERA},42);else if(w==2)startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"));else startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}).show();}
 void customize(){String[] themes={"آبی JARVIS","بنفش آینده‌نگر","سبز نئون","قرمز Iron Man"};new AlertDialog.Builder(this).setTitle("شخصی‌سازی JARVIS").setSingleChoiceItems(themes,Integer.parseInt(secure.get("theme","0")),(d,w)->{secure.put("theme",String.valueOf(w));applyTheme(w);d.dismiss();}).setPositiveButton("انجام شد",null).show();}
 void applyTheme(int t){int[] colors={Color.rgb(90,235,255),Color.rgb(190,100,255),Color.rgb(100,255,170),Color.rgb(255,90,80)};int col=colors[Math.max(0,Math.min(3,t))];status.setTextColor(col);connection.setTextColor(col);hud.setTextColor(col);coreState.setTextColor(col);findViewById(R.id.logo).setBackgroundColor(Color.argb(18,Math.min(255,col+1),Math.min(255,col+1),Math.min(255,col+1)));}
 void notificationMenu(){new AlertDialog.Builder(this).setTitle("پیام‌های دریافتی").setMessage(notes.briefing()).setPositiveButton("پاسخ با تأیید من",(d,w)->confirmReply()).setNeutralButton("دسترسی اعلان‌ها",(d,w)->startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"))).setNegativeButton("بستن",null).show();}
 void confirmReply(){EditText e=new EditText(this);e.setHint("متن پاسخ");e.setText("سلام، پیام شما را دیدم.");new AlertDialog.Builder(this).setTitle("تأیید پاسخ").setMessage(notes.briefing()).setView(e).setPositiveButton("ارسال",(d,w)->{String s=NotificationAction.replyLatest(this,e.getText().toString());respond(s.equals("انجام شد.")?"پاسخ تأییدشده ارسال شد.":s);}).setNegativeButton("لغو",null).show();}
 void setupAI(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText e=new EditText(this);e.setHint("Endpoint");e.setText(secure.get("endpoint","https://api.openai.com/v1/chat/completions"));EditText k=new EditText(this);k.setHint("API Key");k.setText(secure.get("key",""));k.setInputType(129);EditText m=new EditText(this);m.setHint("Model");m.setText(secure.get("model","gpt-4o-mini"));EditText h=new EditText(this);h.setHint("Auth Header");h.setText(secure.get("authHeader","Authorization"));EditText p=new EditText(this);p.setHint("Auth Prefix (خالی = بدون prefix)");p.setText(secure.get("authPrefix","Bearer"));l.addView(e);l.addView(k);l.addView(m);l.addView(h);l.addView(p);new AlertDialog.Builder(this).setTitle("تنظیمات AI / API").setMessage("JARVIS 1.021 اکنون از APIهای OpenAI-compatible با Endpoint، Key، Model و روش احراز هویت قابل تنظیم پشتیبانی می‌کند. کلید API به‌صورت رمزنگاری‌شده ذخیره می‌شود. برای OpenRouter: Endpoint = https://openrouter.ai/api/v1/chat/completions ، Auth Header = Authorization ، Auth Prefix = Bearer.").setView(l).setPositiveButton("ذخیره",(d,w)->{secure.put("endpoint",e.getText().toString());secure.put("key",k.getText().toString());secure.put("model",m.getText().toString());secure.put("authHeader",h.getText().toString());secure.put("authPrefix",p.getText().toString());ai.configure(e.getText().toString(),k.getText().toString(),m.getText().toString(),h.getText().toString(),p.getText().toString());respond("تنظیمات API ذخیره شد.");}).setNegativeButton("لغو",null).show();}
 void passwordGate(){EditText e=new EditText(this);e.setInputType(129);e.setHint("رمز JARVIS");new AlertDialog.Builder(this).setTitle("فعال‌سازی JARVIS").setMessage("رمز فعال‌سازی را وارد کن.").setView(e).setCancelable(false).setPositiveButton("فعال‌سازی",(d,w)->{if("ayhan2012".equals(e.getText().toString())){secure.put("activated","1");respond("فعال‌سازی موفق بود.");}else{Toast.makeText(this,"رمز نادرست است.",Toast.LENGTH_LONG).show();new Handler().postDelayed(this::passwordGate,300);}}).show();}
 void append(String a,String b){chat.append("\n"+a+"  ›  "+b+"\n");}
 void show(String a,String b){new AlertDialog.Builder(this).setTitle(a).setMessage(b).setPositiveButton("باشه",null).show();}
 @Override protected void onDestroy(){vision.stop();localLlm.release();try{unregisterReceiver(wakeReceiver);}catch(Exception e){}super.onDestroy();}
}