package com.jarvis.ai;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.speech.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 static{System.loadLibrary("jarviscore");}private native String nativeProcess(String x);
 TextView chat,status;EditText input;MemoryStore memory;NotificationStore notes;AIClient ai;LanguageManager voice;OfflineEngine offline;ToolRegistry tools;SecureStore secure;CameraController camera;
 BroadcastReceiver wake=new BroadcastReceiver(){public void onReceive(Context c,Intent i){listenOnce();}};
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);chat=findViewById(R.id.chat);status=findViewById(R.id.status);input=findViewById(R.id.input);memory=new MemoryStore(this);notes=new NotificationStore(this);ai=new AIClient();voice=new LanguageManager(this);offline=new OfflineEngine(this);tools=new ToolRegistry();secure=new SecureStore(this);camera=new CameraController();ai.configure(secure.get("endpoint","https://api.openai.com/v1/chat/completions"),secure.get("key",""),secure.get("model","gpt-4o-mini"));
 findViewById(R.id.send).setOnClickListener(v->send());findViewById(R.id.voice).setOnClickListener(v->listenOnce());findViewById(R.id.stop).setOnClickListener(v->voice.speak("",1));findViewById(R.id.memory).setOnClickListener(v->show("MEMORY",memory.recent(40)));findViewById(R.id.briefing).setOnClickListener(v->show("BRIEFING",notes.briefing()));findViewById(R.id.notifications).setOnClickListener(v->startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS")));findViewById(R.id.permissions).setOnClickListener(v->requestPermissions(new String[]{android.Manifest.permission.CAMERA,android.Manifest.permission.RECORD_AUDIO},7));findViewById(R.id.capture).setOnClickListener(v->captureVision());findViewById(R.id.settings).setOnClickListener(v->setupAI());status.setText("JARVIS 1.021 • CORE ONLINE • OFFLINE READY");append("JARVIS","Ready. AI, Vision, voice, tools and long-term memory initialized.");registerReceiver(wake,new IntentFilter("com.jarvis.ai.WAKE"),Context.RECEIVER_NOT_EXPORTED);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},77);}
 void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");append("YOU",q);memory.add("user",q);String local=offline.answer(q);if(local!=null){respond(local);return;}String n=nativeProcess(q);if(!n.startsWith("OPEN-DOMAIN")){respond(n);return;}String l=q.toLowerCase(Locale.ROOT);if(l.startsWith("do ")||l.startsWith("execute ")||l.startsWith("اجرا ")||l.startsWith("باز کن ")){String a=q.replaceFirst("(?i)^(do|execute|اجرا|باز کن)\\s*","");respond(tools.execute(this,a));return;}ai.ask("You are JARVIS 1.021. Be concise and natural. User: "+q+"\nLong-term memory:\n"+memory.recent(16),this::respond);}
 void respond(String s){append("JARVIS",s);memory.add("assistant",s);voice.speak(s,1);}
 void listenOnce(){if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},8);return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);startActivityForResult(i,99);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==99&&c==RESULT_OK&&d!=null){ArrayList<String>x=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));send();}}}
 void captureVision(){if(checkSelfPermission(android.Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.CAMERA},42);return;}status.setText("VISION • CAPTURING");camera.capture(this,b->{ai.vision("Analyze this camera image. Describe what is visible and answer naturally.",b,this::respond);status.setText("JARVIS 1.021 • CORE ONLINE • OFFLINE READY");});}
 void setupAI(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText e=new EditText(this);e.setText(secure.get("endpoint","https://api.openai.com/v1/chat/completions"));EditText k=new EditText(this);k.setText(secure.get("key",""));k.setInputType(129);EditText m=new EditText(this);m.setText(secure.get("model","gpt-4o-mini"));l.addView(e);l.addView(k);l.addView(m);new AlertDialog.Builder(this).setTitle("JARVIS AI SECURITY").setMessage("API key is stored in Android encrypted storage.").setView(l).setPositiveButton("SAVE",(d,w)->{secure.put("endpoint",e.getText().toString());secure.put("key",k.getText().toString());secure.put("model",m.getText().toString());ai.configure(e.getText().toString(),k.getText().toString(),m.getText().toString());respond("AI configuration saved securely.");}).setNegativeButton("CANCEL",null).show();}
 void append(String a,String b){chat.append("\n"+a+": "+b+"\n");}void show(String a,String b){new AlertDialog.Builder(this).setTitle(a).setMessage(b).setPositiveButton("OK",null).show();}protected void onDestroy(){try{unregisterReceiver(wake);}catch(Exception e){}camera.close();super.onDestroy();}
}